### ISSUE TITLE
implementing linear layer with  PHM-layer

### ISSUE THREAD

**Issue by dorost1234** [bayer-science-for-a-better-life/phc-gnn#1]
Hi
thanks for sharing your codes. I am a bit confused on finding the implementation of PHM-layer and how I can turn a linear layer to the more efficient one using the method in the paper to train the models, could you kindly guide me? 
I found this line https://github.com/bayer-science-for-a-better-life/phc-gnn/blob/e802868bea7b9d1cad15c8227b109a8b4ca2a8e7/phc/quaternion/layers.py#L60 not sure if this is the correct one I am looking for, but this seems that linear layer has 4 matrices of size of the original linear layer, then this is even more parameters, could you kindly comment on this?
thanks

**Comment by tuanle618** [comment]
Hey, thanks for your interest :) Indeed, I need to add more documentation on how to use the quaternion and PHM linear layers.

Since you asked for an example to use the PHM-layer, its implementation can be found at: https://github.com/bayer-science-for-a-better-life/phc-gnn/blob/master/phc/hypercomplex/layers.py#L113-L191.

This implementation right now relies on `torch.nn.ParameterList` and might not be optimal, as we can actually store the weight-matrices in an order-3 tensor of shape (phm_dim, in_channels // phm_dim , out_channels // phm_dim).
Hence, right now, before instantiating the PHM-linear layers, the channels have to be divided.

Find the example below.

```python
import torch
from phc.hypercomplex.layers import PHMLinear

in_channels = 128
out_channels = 256

phm_dim = 4

device = "cuda:0" if torch.cuda.is_available() else "cpu"

phm_linear = PHMLinear(in_features=in_channels // phm_dim,
                       out_features=out_channels // phm_dim,
                       bias=True,
                       phm_dim=phm_dim).to(device)

standard_linear = torch.nn.Linear(in_features=in_channels, out_features=out_channels, bias=True).to(device)

def get_num_params(module: torch.nn.Module):
    return sum(m.numel() for m in module.parameters() if m.requires_grad)

print(f"PHM Linear has {get_num_params(phm_linear)} trainable parameters.")
# PHM Linear has 8512 trainable parameters.
print(f"Standard Linear has {get_num_params(standard_linear)} trainable parameters.")
# Standard Linear has 33024 trainable parameters.

x = torch.randn(512, in_channels).to(device)

y0 = phm_linear(x)
print(y0.shape) 
# torch.Size([512, 256])

y1 = standard_linear(x)
print(y1.shape) 
# torch.Size([512, 256])

# the weights for the PHM-layer are saved in the self.W and self.b torch.nn.ParameterList.
print(phm_linear.W)
print(phm_linear.b)
```

Does this answer your question? 

In our GNN implementation, we divide the number of in- and output channels when instantiating the model class.
https://github.com/bayer-science-for-a-better-life/phc-gnn/blob/master/phc/hypercomplex/undirectional/models.py#L73-L74.

Best, 
Tuan.

**Comment by dorost1234** [comment]
Yes, thank you very much, you are the best!
thank you for this wonderful clear response, now I can understand this.

**Comment by dorost1234** [comment]
Hi,
I am still testing the  phm_linear layer, 

a) in general inputs also have batch_size so the input would be of size ```batch_size*x*y``` and then the linear layer needs to output a tensor with dimensions ```batch_size*x*output_dim```, when I test the  PHM Linear with 3D inputs (when it also has batch-size), then I get error, I would greatly appreciate to assist me how I can solve this issue? 

b) could you kindly also comment what is "learn_phm" in this layer? and how this impact the results?

c) In general case, if output_dim and input_dim are not divisible by the "phm_dim", can anything be done for this case?

thank you very much

**Comment by dorost1234** [comment]
could you kindly also comment what is "learn_phm" in this layer? and how this impact the results? thank you

**Comment by tuanle618** [comment]
Our implementation of the PHM-layer considered 2D tensors, hence you have faced the error. In future, I am going to expand the usability of the `PHMLinear` layer, to handle arbitrary sized tensors, like `(N, *, *, ..., in_channels)` similarly to `torch.nn.Linear`. To answer your questions:

(a) To handle multidimensional data `x` with `x.ndim > 2`, you need to use the `torch.matmul` call. To achieve this, please **replace** following line https://github.com/bayer-science-for-a-better-life/phc-gnn/blob/f4f04d1a0350058599380b0d86426f4d7b7eb412/phc/hypercomplex/layers.py#L106 
with 

```python
y = torch.matmul(input=x, other=H.t())
```
Then you should be able to compute the forward pass from the `PHMLinear` module.


(b)
The `learn_phm` parameter refers to the **contribution matrices** C_i in our paper. (See Eq.4) and are set to `True` by default. Recall that when `phm_dim=4`, we use the multiplication rule from the Quaternion Algebra. As the PHM-layer should learn the multiplication rule from data, it is advised to set `learn_phm=True` to obtain better learning behaviour. If you have a fixed multiplication rule, your model can be less flexible and too restrictive with the weight-sharing.
Implementation-wise, the C_i matrices are stored in the `PHMLinear.phm_rule` Parameterlist:
https://github.com/bayer-science-for-a-better-life/phc-gnn/blob/f4f04d1a0350058599380b0d86426f4d7b7eb412/phc/hypercomplex/layers.py#L135

(c) 
If you use the integer-division `//` as I have shown in the example, and your in- and output-channels are **not** divisible by `phm_dim`, then the module will still be able to be instantiate, but your in- and output will be effectively smaller than inserted.
For example, if ``in_channels=257; out_channels=513`` and `phm_dim=4` , then by integer-division, you will have input and output size of 256, and 512, respectively.
To circumvent this, an AssertionError should be raised. I will fix it in future.

Best,
Tuan

**Comment by dorost1234** [comment]
Hi Tuan
Thank you very much for the help, I am really grateful to your help.

(a) I tested it and it works. This is though really very slow, in  the original paper, they mentioned the method takes similar time as original model, Do you have any advice how I can make it faster? I am using it for large-scale and with the current speed I am not able to use  this great work.

(b) I see, so it adds C_i as in eqn (4) for better accuracy, but with trade-off of more parameters.

thanks a lot.

**Comment by tuanle618** [comment]
Hi @dorost1234,

I've pushed a modified `PHMLinearNew` class into a new branch, to further work on in future (https://github.com/bayer-science-for-a-better-life/phc-gnn/blob/improve_phmlin/phc/hypercomplex/layers.py#L195-L297).

I did some changes for the `PHMLinearNew` class:

1.  Include assertion to do the division *within* the class, so you do not need to divide the in- and output channels as I did before.
2. Store the main components to construct the final weight matrix into separate tensors, i.e.:
2a. `W_` component matrices into one tensor of shape (phm_dim, in_channels//phm_dim, out_channels//phm_dim)
2b. `C_` contribution matrices into one tensor of shape (phm_dim, phm_dim, phm_dim)
3. Handle the case to transform multidimensional data `x` , i.e. when `x.ndim > 2` as in your case.

Could you kindly pull the branch and try the `PHMLinearNew` class in your case? To refer to your point (a): I am not sure if it will be much faster, but now the class does not include operations like stacking of tensors. I think the bottleneck might lie in the general computation of the Kronecker product, as it includes many multiplications to expand the seperate order-2 tensors `{(C_i, W_i)}_i=1^{phm_dim}`

To (b)
If your in- and output channels, are actually larger, say > 256, the parameter-share for the phm_rule matrices are comparably small. (See our paper or the original PHM-layer paper).
Find below some sample code to quickly run:

```python
import torch
from phc.hypercomplex.layers import PHMLinear, PHMLinearNew
import time


in_channels = 256
out_channels = 512
batch_size = 512
seq_length = 50
phm_dim = 4

device = "cuda:0" if torch.cuda.is_available() else "cpu"

def get_num_params(module: torch.nn.Module):
    return sum(m.numel() for m in module.parameters() if m.requires_grad)

x = torch.randn((batch_size, seq_length, in_channels), requires_grad=True).to(device)

phm_linear_old = PHMLinear(in_features=in_channels//phm_dim, out_features=out_channels//phm_dim,
                           phm_dim=phm_dim, learn_phm=True, c_init="random", w_init="phm")

get_num_params(phm_linear_old)
# 33344

# params for contribution matrices
get_num_params(phm_linear_old.phm_rule)
# 64

# params for weight-matrix and biases
get_num_params(phm_linear_old) - get_num_params(phm_linear_old.phm_rule)
# 33280

standard_linear = torch.nn.Linear(in_channels, out_channels, bias=True)
get_num_params(standard_linear)
# 131584


# New PHM Layer, NOTE: now the division of in- and output channels is taken care of in the class
phm_linear_new = PHMLinearNew(in_features=in_channels, out_features=out_channels,
                              phm_dim=phm_dim, learn_phm=True, c_init="random", w_init="phm")

assert get_num_params(phm_linear_new) - get_num_params(phm_linear_old) == 0

phm_linear_old = phm_linear_old.to(device)
phm_linear_new = phm_linear_new.to(device)

x = x.to(device)

def benchmark_phm_module(module, iterations):

    start = time.time()
    for i in range(iterations):
        y = module(x)
        l = y.sum()
        l.backward()
    print(f"Execution: {((time.time()-start) / iterations):.6f}s.")


benchmark_phm_module(module=phm_linear_old, iterations=1000)
# Execution: 0.006355s.

benchmark_phm_module(module=phm_linear_new, iterations=1000)
# Execution: 0.005695s.


# sanity implementation check:
# test if the outputs are the same from the old PHMLinear implementation compared to the new one.
W_list = torch.nn.ParameterList([torch.nn.Parameter(Wi.data.t()) for Wi in phm_linear_new.W.data])
phm_rule_list = torch.nn.ParameterList([torch.nn.Parameter(Ci.data.t()) for Ci in phm_linear_new.phm_rule.data])
b = torch.nn.ParameterList([torch.nn.Parameter(bi.data) for bi in phm_linear_new.b.data.chunk(phm_dim)])

# assign weights from PHMLinearNew to PHMLinear
phm_linear_old.W = W_list
phm_linear_old.b = b
phm_linear_old.phm_rule = phm_rule_list

y_old = phm_linear_old(x)
y_new = phm_linear_new(x)

torch.allclose(y_old, y_new)
#Out[29]: True


# 2D data

x = torch.randn((batch_size, in_channels), requires_grad=True).to(device)
y_old = phm_linear_old(x)
y_new = phm_linear_new(x)
torch.norm(y_old - y_new)
#tensor(0.0001)

```

**Comment by dorost1234** [comment]
Dear @tuanle618 

Thank you so much  for the help, this is now far faster, I am impressed by your programming skills, 

- I get Nans with setting " learn_phm=True", and without setting the initialization but without learn_phm=true or setting initialization this seems to work fine, I was wondering if there is a known issue regarding setting learn_phm/intialization? 

    - Specifically, I am getting Nan with setting learn_phm=True and `phm_dim` = 8, but if I set `phm_dim`=4 or 12 I do not seem to get Nans, I really appreciate any intuition on it. Also if I set `phm_dim=8` with setting ` learn_phm=True, c_init="random", w_init="phm"` I do not seem to get NaNs so far, so the initialization seems to matter a lot. 


- regarding the initializations (c_init="random", w_init="phm") , is there an specific ones you would recommend? 

thanks a lot again for the new layer.

**Comment by tuanle618** [comment]
Hi @dorost1234, the `c_init` argument should be set to `random` if you have a larger phm-dimension. For further details, please read in our paper Section 4.1. Intuitively, the contribution matrices `C_i` determine the interaction between the different weight matrices. So if you actually have a larger phm-dim, say 12, then `c_init` with `standard` will lead to difficult learning behaviour. (Appendix D.2) .
Generally, you **should** set `learn_phm=True`, in order to make most of the layer. So in your case with phm-dim to 8, setting `c_init="random"` and `phm_dim=8` seems fine, right? I would recommend this setting, as its also done as default value in the new implementation https://github.com/bayer-science-for-a-better-life/phc-gnn/blob/a7eacc72d11d73ab91c39e4d7625fa7a0b33a4f8/phc/hypercomplex/layers.py#L225.

You are working with sequential data, aren't you? I have only applied the PHM layer in the context of graph representation learning. In order to stabilize training, you might want to include gradient clipping for your entire model, or at least the `phm_rule` tensor of the `PHMLinearNew` class. 
Here's an example for some kind of dummy model, applying [gradient clipping](https://pytorch.org/docs/stable/generated/torch.nn.utils.clip_grad_norm_.html) to the phm-rules.
```python
import torch.nn as nn

class MyModel(nn.Module):
    def __init__(self):
        super(MyModel, self).__init__()
        """
        Build some kind of model with different nn.Modules
        """
        self.relu = nn.ReLU()
        self.lin1 = nn.Linear(128, 128)
        self.lin2 = nn.Linear(128, 128)
        self.rnn = nn.GRUCell(128, 128)
        self.phmlin = PHMLinearNew(128, 128, phm_dim=4, w_init="phm", learn_phm=True, c_init="random")
        self.phmlin2 = PHMLinearNew(128, 128, phm_dim=4, w_init="phm", learn_phm=True, c_init="random")

    def forward(self, x):
        return x



model = MyModel()
phm_rule_list = []
for name, module in model.named_modules():
    if hasattr(module, "phm_rule"):
        m = getattr(module, "phm_rule")
        phm_rule_list.append(m)


assert len(phm_rule_list) == 2
torch.nn.utils.clip_grad_norm_(phm_rule_list, max_norm=1.0, norm_type=2.0) # does operation in-place.
```

**Comment by dorost1234** [comment]
Dear @tuanle618 
Thank you very much for the response, I tried it but so far, I am getting very low results with PHM layers (I used the setting you mentioned), I would be really thankful if you could give me some intuition how initialization is related to PHM_DIM, is this for some dimensions one should choose a different setting? I kept it as you mentioned for all setting, I also greatly appreciate any suggestions on how I can improve the results with PHM layers. Thank you very much.

**Comment by tuanle618** [comment]
The initialization for the contribution matrices `C_i` should be said to `random`, if you have a larger phm-dimension. Without any further details from you, I cannot help with improving the PHM-layer. As said, its 'just' a layer for affine transformation, a small, yet important building block within your model. Maybe reducing the phm-dimension helps. Choose `phm_dim=4` instead. How large is your model in general ? what is the embedding size?

**Comment by dorost1234** [comment]
Dear @tuanle618 

- My embedding size is 768, and my model is 110 M parameters (Bert-base-uncased).  I am using Bert for sequence classification.

- when I set phm_train to true, I get 30% less accuracy, since in the original paper when they apply it on a transformer model, it gets roughly the same results, and I think original paper is with having phm_rules set to train.

-  setting phm_dim to 4 helps, but the results are still worst than phm-dim = 8 without training phm_rules. 

- I also applied gradient clipping, it only sometimes solves the nan, and accuracies are still the same with it.

- I also tried with other intialization, I make the self.W with dimensions of (phm_dim=4, self._in_feats_per_axis=192, self._out_feats_per_axis=6), but if one set w_init to "glorot-normal", I am getting this error:

```
  raise ValueError("Fan in and fan out can not be computed for tensor with fewer than 2 dimensions")
ValueError: Fan in and fan out can not be computed for tensor with fewer than 2 dimensions
```
- I also tried to init the weight with random so I did:
```
self.W.data = nn.init.normal_(self.W.data, std=1e-2)
```
this results in the following error:
```
  File "/users/dara/dev/codes/hypercomplex/layers.py", line 219, in forward
    return matvec_product_new(W=self.W, x=x, bias=self.b, phm_rule=self.phm_rule)
  File "/users/dara/dev/codes/hypercomplex/layers.py", line 141, in matvec_product_new
    H = kronecker_product_einsum_batched(phm_rule, W).sum(0)
  File "/users/dara/dev/codes/hypercomplex/kronecker.py", line 29, in kronecker_product_einsum_batched
    assert A.dim() == 3 and B.dim() == 3
AssertionError
```
- I was wondering why you have chosen this initialization for bias term:
```
 if self.bias_flag:
            self.b.data[:self._out_feats_per_axis] = 0.0
            self.b.data[(self._out_feats_per_axis+1):] = 0.2
```

I really appreciate any suggestions.

**Comment by dorost1234** [comment]
I would be grateful if you could kindly mention why you have chosen this initialization 

```
 if self.bias_flag:
            self.b.data[:self._out_feats_per_axis] = 0.0
            self.b.data[(self._out_feats_per_axis+1):] = 0.2
```

thanks

**Comment by tuanle618** [comment]
Hey @dorost1234 , 

- I also tried with other intialization, I make the self.W with dimensions of (phm_dim=4, self._in_feats_per_axis=192, self._out_feats_per_axis=6), but if one set w_init to "glorot-normal", I am getting this error:

--> I fixed the issue with the `glorot-uniform` or `glorot-normal` initialisation. Please pull the recent `improve_phmlin`branch to have the new version.

- self.W.data = nn.init.normal_(self.W.data, std=1e-2) --> this wont work, as the self.W tensor should be of order 3, i.e. with shape (phm_dim, in_feats_per_axis, out_feats_per_axis). Now, with the bugfix mentioned above, you should be fine. Otherwise, redefine the weight-initialisation in the `PHMLinearNew` class but make sure, in the end the self.W tensor has the shape I mentioned.

-  I initialised the bias term is this way, as such initialisation improved the training in my graph learning tasks. Usually biases are init. as 0, but when I did it, I faced almost no changing of the biases values during training.

Since I used PHM in the context of graph representation learning, I cannot help you much. I guess it's a lot of trial and error. I can imagine in your case, the initialisation is crucial. Maybe you could contact the original authors of the PHM-layer and asked for more details. For the `learn_phm` value: I believe this should be set to `True` as in the default. I modified the code, you can also initialise the contribution matrices differently, see: https://github.com/bayer-science-for-a-better-life/phc-gnn/blob/improve_phmlin/phc/hypercomplex/layers.py#L279-L280

You could try different initialisation schemes. I'd also use gradient clipping during training. `NaN` values are likely obtained by too large numbers. So the initialisation scheme ought be changed, such that the values in the tensors are (pretty) much smaller. But I can't tell exactly, as I do not have your kind of data and applied the PHM in a different application.

Hope this helps. Let me know if you need further assistance.

**Comment by dorost1234** [comment]
Dear @tuanle618 
could you give me some hints how I can understand how to choose the initialization? I honestly dont see much options to play with.
for me it does not at all train, so I get the same loss over and over.
For instance if I change W initiziation to normal as ```self.W.data.normal_(std=0.01)``` then this gets Nan,  but not if this is set to "phm" initialization, could you kindly tell me how I can understand which parameters to play with? and get some intuition how to set them? thanks

**Comment by tuanle618** [comment]
Hi @dorost1234 , 

For further details on the standard phm initialization please read the appendix of our paper. 

I think in general, you need to initialize the weights of the separate weight matrices W_i drawing from a normal or uniform distribution with a small standard deviation. As all the matrices are stored in self.W with shape (in_feats_per_axis, out_feats_per_axis) along the phm dimension, resulting to (phm_dim, in_feats_per_axis, out_feats_per_axis), you can also just stack all matrices into one 2D tensor, do the standard glorot normal/uniform matrix and then call torch.chunk(W, chunks=phm_dim, dim=1) to obtain the separate weight matrices to store as order-3 tensor.

With our provided initialization (phm, glorot-normal, glorot-uniform) our models were able to train. How this translates to transformer networks: I don't know, as this was not my application. In the code you can see how the weights are initialized, so it's up to you know how to proceed. My suggestion would be to initialize the weight matrix with the full dimension, i.e. Shape (in_feats, out_feats) , do the init with glorot or he (check torch.nn.inits module), and then do the chunking with torch.chunk to store the parameters into self.W as order-3 tensor so it has shape (phm_dim, in_feats_per_axis, out_feats_per_axis).

And for the self.phm_rule tensor of shape (phm_dim, phm_dim, phm_dim) you could also try initialize them from a normal distribution with mean 0.0 and standard deviation 0.5. (or try different standard deviations between 0.1 to 1.0)


Recall that the 'final' weight matrix used for the linear transformation is a sum of kronecker products. That means, that if the product is already too small, you are likely to face underflow. I hope you can find a solution.

**Comment by dorost1234** [comment]
thanks a lot
