### ISSUE TITLE
making PHM layers faster

### ISSUE THREAD

**Issue by dorooddorood606** [bayer-science-for-a-better-life/phc-gnn#5]
Hi
I observe speed difference between the PHM layers and linear layers, while in the original paper they clarim the running time should be the same, could you kindly let me know if you might know a way I could make the running time faster? greatly appreciated.

**Comment by tuanle618** [comment]
Hey, please check the branch `improve_phmlin`: https://github.com/bayer-science-for-a-better-life/phc-gnn/blob/improve_phmlin/phc/hypercomplex/layers.py#L114

I have implemented a different version. See Issue #1 

If you import this module, it might be faster. Let me know if it works.
